# chargement de spark

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [37]:
%timeit

In [264]:
from pyspark.sql.types     import *
from pyspark.sql.functions import udf
multiplie_par = udf(multiplie_par_2, FloatType())

In [187]:
r = []
for i in dir(df):
    try:
        if "_" not in i:
            exec("_ = df.%s.__doc__ ;  "%(i))
            exec("param = df.%s.__code__.co_varnames[1:]"%(i))
            r.append({ "function" : i, 
                       "parametres" : param, 
                      "Details" : _.strip().split("\n")[0]})
    except Exception as e:
        print(e)
        pass

'list' object has no attribute '__code__'
'list' object has no attribute '__code__'
'bool' object has no attribute '__code__'
'DataFrameNaFunctions' object has no attribute '__code__'
'RDD' object has no attribute '__code__'
'StructType' object has no attribute '__code__'
'DataFrameStatFunctions' object has no attribute '__code__'
'StorageLevel' object has no attribute '__code__'
'DataFrameWriter' object has no attribute '__code__'
"'writeStream' can be called only on streaming Dataset/DataFrame;"

In [191]:
pd.DataFrame(r)[["function", "parametres", "Details"]].to_excel("df_functions.xlsx")

In [162]:
r.keys()

dict_keys(['Automatically created module for IPython interactive environment', <class 'filter'>])

In [157]:
_

':func:`drop_duplicates` is an alias for :func:`dropDuplicates`.\n\n.. versionadded:: 1.4'

In [75]:
docu = []
for k in sorted(dir(df)):
    if "_" not in k:
        try:
            doc = F.__dict__[k].__doc__.split("\n")[1]
            parameters = F.__dict__[k].__code__.co_varnames[:-1]
            if doc:
                docu.append([k, parameters,doc])
        except:
            pass

1049

In [77]:
from pyspark.sql import functions as F

In [78]:
df.count()

1049

In [137]:
docu = []
for k in sorted(F.__dict__.keys()):
    if "_" not in k:
        try:
            doc = F.__dict__[k].__doc__.split("\n")[1]
            parameters = F.__dict__[k].__code__.co_varnames[:-1]
            if doc:
                docu.append([k, parameters,doc])
        except:
            pass

In [138]:
import pandas as pd

In [139]:
df = pd.DataFrame(docu)

In [140]:
df

,0,1,2
0,approxCountDistinct,"(col, rsd)",".. note:: Deprecated in 2.1, use :func:`ap..."
1,atan2,"(col1, col2, sc, jc)",:param col1: coordinate on y-axis
2,bround,"(col, scale, sc)",Round the given value to `scale` decimal p...
3,concat,"(cols, sc)",Concatenates multiple input columns togeth...
4,conv,"(col, fromBase, toBase, sc)",Convert a number in a string column from o...
5,corr,"(col1, col2, sc)",and ``col2``.
6,cos,"(col, sc, jc)",":return: cosine of the angle, as if..."
7,cosh,"(col, sc, jc)",:return: hyperbolic cosine of the a...
8,crc32,"(col, sc)",Calculates the cyclic redundancy check val...
9,datediff,"(end, start, sc)",Returns the number of days from `start` to...
10,dayofmonth,"(col, sc)",Extract the day of the month of a given da...
11,dayofweek,"(col, sc)",Extract the day of the week of a given dat...
12,dayofyear,"(col, sc)",Extract the day of the year of a given dat...
13,decode,"(col, charset, sc)",Computes the first argument into a string ...
14,degrees,"(col, sc, jc)",Converts an angle measured in r...
15,encode,"(col, charset, sc)",Computes the first argument into a binary ...
16,factorial,"(col, sc)",Computes the factorial of the given value.
17,flatten,"(col, sc)",Collection function: creates a single arra...
18,greatest,"(cols, sc)",Returns the greatest value of the list of ...
19,grouping,"(col, sc, jc)",Aggregate function: indicates whether a sp...
20,hex,"(col, sc, jc)",":class:`pyspark.sql.types.BinaryType`, :cl..."
21,hour,"(col, sc)",Extract the hours of a given date as integer.
22,instr,"(str, substr, sc)",Locate the position of the first occurrenc...
23,lag,"(col, count, default, sc)",Window function: returns the value that is...
24,lead,"(col, count, default, sc)",Window function: returns the value that is...
25,least,"(cols, sc)",Returns the least value of the list of col...
26,length,"(col, sc)",The length of character data includes the ...
27,lit,"(col, sc, jc)",Creates a :class:`Column` of literal value.
28,locate,"(substr, str, pos, sc)",Locate the position of the first occurrenc...
29,lpad,"(col, len, pad, sc)",Left-pad the string column to width `len` ...
...,...,...,...
32,ntile,"(n, sc)",Window function: returns the ntile group i...
33,quarter,"(col, sc)",Extract the quarter of a given date as int...
34,radians,"(col, sc, jc)",Converts an angle measured in d...
35,rand,"(seed, sc, jc)","from U[0.0, 1.0]."
36,randn,"(seed, sc, jc)",the standard normal distribution.
37,repeat,"(col, n, sc)","Repeats a string column n times, and retur..."
38,reverse,"(col, sc)",Collection function: returns a reversed st...
39,round,"(col, scale, sc)",Round the given value to `scale` decimal p...
40,rpad,"(col, len, pad, sc)",Right-pad the string column to width `len`...
41,second,"(col, sc)",Extract the seconds of a given date as int...
42,sequence,"(start, stop, step, sc)",Generate a sequence of integers from `star...
43,sha2,"(col, numBits, sc, jc)",and SHA-512). The numBits indicates the de...
44,shuffle,"(col, sc)",Collection function: Generates a random pe...
45,sin,"(col, sc, jc)",":return: sine of the angle, as if c..."
46,since,"(version, re, deco)",A decorator that annotates a function to a...
47,sinh,"(col, sc, jc)",:return: hyperbolic sine of the giv...
48,size,"(col, sc)",Collection function: returns the length of...
49,slice,"(x, start, length, sc)",Collection function: returns an array cont...
50,soundex,"(col, sc)",Returns the SoundEx encoding for a string
51,split,"(str, pattern, sc)",Splits str around pattern (pattern is a re...
52,substring,"(str, pos, len, sc)",Substring starts at `pos` and is of length...
53,tan,"(col, sc, jc)",:return: tangent of the given value...
54,tanh,"(col, sc, jc)",:return: hyperbolic tangent of the...
55,translate,"(srcCol, matching, replace, sc)",The characters in `replace` is correspondi...
56,trunc,"(date, format, sc)",Returns date truncated to the unit specifi...
57,unhex,"(col, sc)",and converts to the byte representation of...
58,weekofyear,"(col, sc)",Extract the week number of a given date as...
59,when,"(condition, value, sc, v, jc)",If :func:`Column.otherwise` is not invoked...
60,window,"(timeColumn, windowDuration, slideDuration, st...",starts are inclusive but the window ends a...
61,year,"(col, sc)",Extract the year of a given date as integer.

In [136]:
df.to_excel("F_doc.xlsx")

In [110]:
!pwd

/home/jovyan/work

In [111]:
!ls

2_charger_de_la_donnee.ipynb  livre_spark_notebook_1.ipynb  Untitled.ipynb
F_doc.xlsx		      spark-warehouse